package net.prayforyou.backend.domain.battle.enums

enum class BattlePlaceType(
    val description: String
) {
    SUPPLY01("텔포자리"),
    SUPPLY02("매박"),
    SUPPLY03("숏인"),
    SUPPLY04("숏 바닥"),
    SUPPLY05("숏 녹깡 위"),
    SUPPLY06("중길"),
    SUPPLY07("롱길"),
    SUPPLY08("롱녹위, 롱녹뒤"),
    SUPPLY09("롱녹깡앞"),
    SUPPLY10("머리길"),
    SUPPLY11("가로등"),
    SUPPLY12("숏앞"),
    SUPPLY13("에롱 45도"),
    SUPPLY14("컨사이"),
    SUPPLY15("3미리 컨뒤"),
    SUPPLY16("중 컨뒤"),
    SUPPLY17("중 컨앞"),
    SUPPLY18("에이 설대"),
    SUPPLY19("쓰리깡"),
    SUPPLY20("설 컨앞"),
    SUPPLY21("숏녹깡 왼쪽"),
    SUPPLY22("숏녹깡 오른쪽"),
    SUPPLY23("니은자"),
    SUPPLY24("리베 에이 백업 자리"),
    SUPPLY25("일문"),
    SUPPLY26("계끝"),
    SUPPLY27("빽창"),
    SUPPLY28("앞창"),
    SUPPLY29("삼거리"),
    SUPPLY30("사무실"),
    SUPPLY31("앵글"),
    SUPPLY32("빽난간"),
    SUPPLY33("1기 2기 아웃코스"),
    SUPPLY34("2기 3기 아웃코스"),
    SUPPLY35("3기 4기 아웃코스"),
    SUPPLY36("앵글 앞 인코스"),
    SUPPLY37("전난"),
    SUPPLY38("비 중통앞"),
    SUPPLY39("비 인코스 1번"),
    SUPPLY40("비 인코스 2번"),
    SUPPLY41("비 인코스 3번"),
    SUPPLY42("5철"),
    SUPPLY43("비설대"),
    SUPPLY44("비롱"),
    SUPPLY45("디귿자"),
    SUPPLY46("비끝"),
    SUPPLY47("난간 타는 박스"),
    SUPPLY48("에이 적베"),
    SUPPLY49("홀"),
    SUPPLY50("달방, 달방위"),
    SUPPLY51("짝방"),
    SUPPLY52("반계"),
    SUPPLY53("와리"),
    SUPPLY54("기억자"),
    SUPPLY55("난간"),
    SUPPLY56("홀입구"),
    SUPPLY57("역개 털리는 자리"),
    NO_POSITION("미식별");
}
