server:
  forward-headers-strategy: framework
spring:
  datasource:
    url: jdbc:mysql://database-1.cr6mwomo4s1d.ap-northeast-2.rds.amazonaws.com/supply
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: rladudtjr1!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: update           # 이 옵션은 테이블을 자동으로 업데이트하지만 외래 키 제약을 비활성화할 수 있음
        # 외래 키 제약 비활성화 설정
        javax.persistence.schema-generation.scripts.create-target: none
        hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create  # 애플리케이션 시작 시 데이터베이스 스키마를 자동으로 업데이트
    database-platform: org.hibernate.dialect.MySQL8Dialect
