spring:

  datasource:
    url: jdbc:mysql://localhost:3306/supply?useSSL=false&allowPublicKeyRetrieval=true&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    open-in-view: false
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect

decorator:
  datasource:
    p6spy:
      enable-logging: true
